from enum import IntEnum


class Gest(IntEnum):
    """
    Gesture ids used across recognizer and controller.

    Values 0..31 follow binary finger-state encoding conventions from the
    original implementation. Values 33+ are custom/special gesture labels
    generated by additional geometric rules (e.g., pinch and V gesture).
    """

    FIST = 0
    PINKY = 1
    RING = 2
    MID = 4
    LAST3 = 7
    INDEX = 8
    FIRST2 = 12
    LAST4 = 15
    THUMB = 16
    PALM = 31

    # Extra mappings
    V_GEST = 33
    TWO_FINGER_CLOSED = 34
    PINCH_MAJOR = 35
    PINCH_MINOR = 36
    THUMBS_UP = 37


class HLabel(IntEnum):
    """Project-level hand roles: major hand vs minor hand."""

    MINOR = 0
    MAJOR = 1
